# this is the set of all counties that are not reporting
# ballot status to the Secretary of State
# TODO: complete this set
counties_not_reporting = {
    'Cerro Gordo',
    'Des Moines',
    'Polk'
}

county_csv_headers = {
    'LAST_NAME': 'last_name',
    'FIRST_NAME': 'first_name',
    'MIDDLE_NAME': 'middle_name',
    'NAME_SUFFIX': 'name_suffix',
    'COUNTY': 'county',
    'REGN_NUM': 'registration_number',
    'DATE_OF_BIRTH': 'date_of_birth',
    'RES_ADD': 'resident_address',
    'MAILING_ADDRESS': 'mailing_address',
    'ABSENTEE_ADDRESS': 'absentee_address',
    'PHONE_NUMBER': 'phone_number',
    'CITY': 'city',
    'STATE': 'state',
    'ZIP': 'zip',
    'VOTERSTATUS': 'voter_status',
    'PARTY': 'party',
    'PRECINCT': 'precinct',
    'BALLOTSTATUS': 'ballot_status',
    'REQUEST_DATE': 'request_date',
    'SENT_DATE': 'sent_date',
    'RECEIVE_DATE': 'receive_date',
    'IS_VOID': 'is_void',
    'COMMENTS': 'comments',
    'ABSENTEE_SEQUENCE_NUMBER': 'absentee_sequence_number',
    'ABSENTEE_ISSUE_METHOD': 'absentee_issue_method',
    'ABSENTEE_RECEIVE_METHOD': 'absentee_receive_method',
    'SPLIT': 'split'
}

display_names = {
    'last_name': 'Last Name',
    'first_name': 'First Name',
    'middle_name': 'Middle Name',
    'name_suffix': 'Suffix',
    'county': 'County',
    'registration_number': 'Voter ID',
    'date_of_birth': 'DOB',
    'resident_address': 'Resident Address',
    'mailing_address': 'Mailing Address',
    'absentee_address': 'Absentee Address',
    'phone_number': 'Phone Number',
    'city': 'City',
    'state': 'State',
    'zip': 'Zip',
    'voter_status': 'Voter Status',
    'party': 'Party',
    'precinct': 'Precinct',
    'ballot_status': 'Ballot Status',
    'request_date': 'Request Date',
    'sent_date': 'Sent Date',
    'receive_date': 'Receive Date',
    'is_void': 'Void',
    'comments': 'Comments',
    'absentee_sequence_number': 'Absentee Sequence Number',
    'absentee_issue_method': 'Absentee Issue Method',
    'absentee_receive_method': 'Absentee Receive Method',
    'split': 'Split'
}

primary_sql_keys = ['last_name', 'first_name', 'middle_name', 'name_suffix', 'resident_address']

date_keys = {'request_date', 'sent_date', 'receive_date', 'date_of_birth'}

code_county_map = {
    '01': {'fips_code': '001', 'name': 'Adair'},
    '02': {'fips_code': '003', 'name': 'Adams'},
    '03': {'fips_code': '005', 'name': 'Allamakee'},
    '04': {'fips_code': '007', 'name': 'Appanoose'},
    '05': {'fips_code': '009', 'name': 'Audubon'},
    '06': {'fips_code': '011', 'name': 'Benton'},
    '07': {'fips_code': '013', 'name': 'Black Hawk'},
    '08': {'fips_code': '015', 'name': 'Boone'},
    '09': {'fips_code': '017', 'name': 'Bremer'},
    '10': {'fips_code': '019', 'name': 'Buchanan'},
    '11': {'fips_code': '021', 'name': 'Buena Vista'},
    '12': {'fips_code': '023', 'name': 'Butler'},
    '13': {'fips_code': '025', 'name': 'Calhoun'},
    '14': {'fips_code': '027', 'name': 'Carroll'},
    '15': {'fips_code': '029', 'name': 'Cass'},
    '16': {'fips_code': '031', 'name': 'Cedar'},
    '17': {'fips_code': '033', 'name': 'Cerro Gordo'},
    '18': {'fips_code': '035', 'name': 'Cherokee'},
    '19': {'fips_code': '037', 'name': 'Chickasaw'},
    '20': {'fips_code': '039', 'name': 'Clarke'},
    '21': {'fips_code': '041', 'name': 'Clay'},
    '22': {'fips_code': '043', 'name': 'Clayton'},
    '23': {'fips_code': '045', 'name': 'Clinton'},
    '24': {'fips_code': '047', 'name': 'Crawford'},
    '25': {'fips_code': '049', 'name': 'Dallas'},
    '26': {'fips_code': '051', 'name': 'Davis'},
    '27': {'fips_code': '053', 'name': 'Decatur'},
    '28': {'fips_code': '055', 'name': 'Delaware'},
    '29': {'fips_code': '057', 'name': 'Des Moines'},
    '30': {'fips_code': '059', 'name': 'Dickinson'},
    '31': {'fips_code': '061', 'name': 'Dubuque'},
    '32': {'fips_code': '063', 'name': 'Emmet'},
    '33': {'fips_code': '065', 'name': 'Fayette'},
    '34': {'fips_code': '067', 'name': 'Floyd'},
    '35': {'fips_code': '069', 'name': 'Franklin'},
    '36': {'fips_code': '071', 'name': 'Fremont'},
    '37': {'fips_code': '073', 'name': 'Greene'},
    '38': {'fips_code': '075', 'name': 'Grundy'},
    '39': {'fips_code': '077', 'name': 'Guthrie'},
    '40': {'fips_code': '079', 'name': 'Hamilton'},
    '41': {'fips_code': '081', 'name': 'Hancock'},
    '42': {'fips_code': '083', 'name': 'Hardin'},
    '43': {'fips_code': '085', 'name': 'Harrison'},
    '44': {'fips_code': '087', 'name': 'Henry'},
    '45': {'fips_code': '089', 'name': 'Howard'},
    '46': {'fips_code': '091', 'name': 'Humboldt'},
    '47': {'fips_code': '093', 'name': 'Ida'},
    '48': {'fips_code': '095', 'name': 'Iowa'},
    '49': {'fips_code': '097', 'name': 'Jackson'},
    '50': {'fips_code': '099', 'name': 'Jasper'},
    '51': {'fips_code': '101', 'name': 'Jefferson'},
    '52': {'fips_code': '103', 'name': 'Johnson'},
    '53': {'fips_code': '105', 'name': 'Jones'},
    '54': {'fips_code': '107', 'name': 'Keokuk'},
    '55': {'fips_code': '109', 'name': 'Kossuth'},
    '56': {'fips_code': '111', 'name': 'Lee'},
    '57': {'fips_code': '113', 'name': 'Linn'},
    '58': {'fips_code': '115', 'name': 'Louisa'},
    '59': {'fips_code': '117', 'name': 'Lucas'},
    '60': {'fips_code': '119', 'name': 'Lyon'},
    '61': {'fips_code': '121', 'name': 'Madison'},
    '62': {'fips_code': '123', 'name': 'Mahaska'},
    '63': {'fips_code': '125', 'name': 'Marion'},
    '64': {'fips_code': '127', 'name': 'Marshall'},
    '65': {'fips_code': '129', 'name': 'Mills'},
    '66': {'fips_code': '131', 'name': 'Mitchell'},
    '67': {'fips_code': '133', 'name': 'Monona'},
    '68': {'fips_code': '135', 'name': 'Monroe'},
    '69': {'fips_code': '137', 'name': 'Montgomery'},
    '70': {'fips_code': '139', 'name': 'Muscatine'},
    '71': {'fips_code': '141', 'name': "O'Brien"},
    '72': {'fips_code': '143', 'name': 'Osceola'},
    '73': {'fips_code': '145', 'name': 'Page'},
    '74': {'fips_code': '147', 'name': 'Palo Alto'},
    '75': {'fips_code': '149', 'name': 'Plymouth'},
    '76': {'fips_code': '151', 'name': 'Pocahontas'},
    '77': {'fips_code': '153', 'name': 'Polk'},
    '78': {'fips_code': '155', 'name': 'Pottawattamie'},
    '79': {'fips_code': '157', 'name': 'Poweshiek'},
    '80': {'fips_code': '159', 'name': 'Ringgold'},
    '81': {'fips_code': '161', 'name': 'Sac'},
    '82': {'fips_code': '163', 'name': 'Scott'},
    '83': {'fips_code': '165', 'name': 'Shelby'},
    '84': {'fips_code': '167', 'name': 'Sioux'},
    '85': {'fips_code': '169', 'name': 'Story'},
    '86': {'fips_code': '171', 'name': 'Tama'},
    '87': {'fips_code': '173', 'name': 'Taylor'},
    '88': {'fips_code': '175', 'name': 'Union'},
    '89': {'fips_code': '177', 'name': 'Van Buren'},
    '90': {'fips_code': '179', 'name': 'Wapello'},
    '91': {'fips_code': '181', 'name': 'Warren'},
    '92': {'fips_code': '183', 'name': 'Washington'},
    '93': {'fips_code': '185', 'name': 'Wayne'},
    '94': {'fips_code': '187', 'name': 'Webster'},
    '95': {'fips_code': '189', 'name': 'Winnebago'},
    '96': {'fips_code': '191', 'name': 'Winneshiek'},
    '97': {'fips_code': '193', 'name': 'Woodbury'},
    '98': {'fips_code': '195', 'name': 'Worth'},
    '99': {'fips_code': '197', 'name': 'Wright'}
}

county_names = [v['name'] for _, v in code_county_map.items()]

# None: None because there are excess columns in some row that exceed the number of headers
sos_csv_headers = {
    'COUNTY_CODE': None,
    'ELECTION_DATE': None,
    'PRECINCT_CODE': 'precinct',
    'PRECINCT_NAME': None,
    'STATE_HOUSE_NAME': None,
    'STATE_SENATE_NAME': None,
    'CONGRESSIONAL': None,
    'POLITICAL_PARTY': 'party',
    'IS_VOID': 'is_void',
    'REQUEST_DATE': 'request_date',
    'SENT_DATE': 'sent_date',
    'RECEIVED_DATE': 'receive_date',
    'VOTER_ID': 'registration_number',
    'STATUS': 'voter_status',
    'FIRST_NAME': 'first_name',
    'MIDDLE_NAME': 'middle_name',
    'LAST_NAME': 'last_name',
    'NAME_SUFFIX': 'name_suffix',
    'RESIDENTIAL_ADDRESS_LINE_1': 'resident_address',
    'CT_CITY': 'city',
    'CT_ST_STATE': 'state',
    'ZIP_ZIP_CODE': 'zip',
    'ZIP_PLUS': None,
    'HOME_PHONE': 'phone_number',
    'MODIFIED_DATE': None,
    'IS_STANDARD': None,
    'ABSENTEE_SEQUENCE_NUMBER': 'absentee_sequence_number',
    'ABSENTEE_ISSUE_METHOD': 'absentee_issue_method',
    'RECEIVE_METHOD': 'absentee_receive_method',
    'DATE_OF_BIRTH': 'date_of_birth',
    'MAIL_ADDRESS': None,
    'MAIL_CITY': None,
    'MAIL_STATE': None,
    'MAIL_ZIP': None,
    'MAIL_ZIP_PLUS': None,
    'FPCA': None,
    'BALLOT_STATUS': 'ballot_status',
    'COMMENTS': 'comments',
    'SPLIT': 'split',
}

voter_demographics_keys = [
    'registration_number',
    'party',
    'ballot_status',
    'county',
    'reject_date',
    'cure_date',
    'age',
    'ethnicity',
    'biden_support_score',
    'biden_turnout_score',
    'dscc_support_score',
    'dscc_turnout_score',
    'biden_support_bucket',
    'dscc_support_bucket',
    'voting_street_address',
    'voting_street_address_2',
    'voting_city',
    'voting_zip',
    'voting_zip4',
    'voting_address_latitude',
    'voting_address_longitude',
    'voting_address_geocode_level',
    'voting_address_type',
    'voting_address_multi_tenant',
    'voting_address_timezone',
    'mailing_address_id',
    'mailing_street_address',
    'mailing_street_address_2',
    'mailing_city',
    'mailing_zip',
    'mailing_zip4',
    'mailing_state',
    'mailing_address_type',
    'best_number',
    'best_number_type',
    'best_number_wrong_number_score',
    'best_number_quality_score',
    'best_number_2',
    'best_number_2_type',
    'best_number_2_wrong_number_score',
    'best_number_2_quality_score',
    'best_number_3',
    'best_number_3_type',
    'best_number_3_wrong_number_score',
    'best_number_3_quality_score',
    'cell',
    'cell_wrong_number_score',
    'cell_quality_score',
    'cell_2',
    'cell_2_wrong_number_score',
    'cell_2_quality_score',
    'cell_3',
    'cell_3_wrong_number_score',
    'cell_3_quality_score',
    'landline',
    'landline_wrong_number_score',
    'landline_quality_score',
    'landline_2',
    'landline_2_wrong_number_score',
    'landline_2_quality_score',
    'landline_3',
    'landline_3_wrong_number_score',
    'landline_3_quality_score',
    'van_id'
]

consolidated_demographics_keys = [
    'county',
    'demographic',
    'total_votes',
    'category'
]

survey_responses_keys = [
    'registration_number',
    'myv_van_id',
    'van_status',
    'van_status_date',
    'auditor_contact',
    'auditor_contact_date',
    'has_plan',
    'has_plan_date',
    'plan',
    'plan_date',
    'number_attempts',
    'phone_attempts',
    'text_attempts',
    'number_canvasses',
    'phone_canvasses',
    'text_canvasses',
    'most_recent_contact_attempt',
    'follow_up',
    'follow_up_date'
]

qid_question_map = {
    '427730': 'van_status',
    '427745': 'auditor_contact',
    '427948': 'has_plan',
    '427736': 'plan',
    '431668': 'follow_up'
}

rid_response_map = {
    '1746381': 'Defective',
    '1746382': 'Deficient',
    '1746383': 'Other',
    '1746384': 'Cured / New Ballot',
    '1746437': 'Yes',
    '1746438': 'No',
    '-1': 'No response',
    '1747278': 'Has plan',
    '1747279': 'No plan',
    '1747277': 'Already acted',
    '1746404': 'Vote by mail',
    '1746403': 'Early vote in person',
    '1746405': 'Vote on election day',
    '1746402': 'Sign at auditor\'s',
    '1761843': 'Yes',
    '1761844': 'No'
}

van_to_clarity = {
    'Voter File VANID': 'van_id',
    'mAddress': 'mailing_address', 
    'mCity': 'mailing_city',
    'mState': 'mailing_state',
    'mZip5': 'mailing_zip',
    'mZip4': 'mailing_zip_4',
    'Sex': 'sex',
    'Address': 'address',
    'City': 'city',
    'State': 'state',
    'Zip5': 'zip',
    'Zip4': 'zip_4',
    'LastName': 'last',
    'FirstName': 'first',
    'MiddleName': 'middle',
    'Suffix': 'suffix',
    'PreferredEmail': 'email',
}
